export const dashboard = <i className="fa-solid fa-chart-line"></i>
export const transactions = <i className="fa-solid fa-credit-card"></i>
export const categories = <i className="fa-solid fa-tags"></i>
export const accounts = <i className="fa-solid fa-wallet"></i>
export const settings = <i className="fa-solid fa-cog"></i>
export const logout = <i className="fa-solid fa-sign-out"></i>
export const trend = <i className="fa-solid fa-money-bill-trend-up"></i>
export const expenses = <i className="fa-solid fa-money-bill-transfer"></i>
export const money = <i className="fa-solid fa-money-bill"></i>
export const freelance = <i className="fa-solid fa-laptop-code"></i>
export const other = <i class="fa-solid fa-ellipsis"></i>
export const contentCreation = <i className="fa-solid fa-video"></i>
export const card = <i className="fa-solid fa-building-columns"></i>
export const rupee = <i className="fa-solid fa-indian-rupee-sign"></i>
export const calender = <i className="fa-solid fa-calendar"></i>
export const comment = <i className="fa-solid fa-comment"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash"></i>
export const signout = <i className="fa-solid fa-right-from-bracket"></i>
export const takeaway = <i class="fa-solid fa-pizza-slice"></i>
export const clothing = <i className="fa-solid fa-shirt"></i>
export const book = <i className="fa-solid fa-book-open"></i>
export const food = <i className="fa-solid fa-utensils"></i>
export const tv = <i className="fa-solid fa-tv"></i>
export const plane = <i class="fa-solid fa-plane"></i>
export const cart = <i class="fa-solid fa-cart-shopping"></i>